"Filed out from Dolphin Smalltalk"!

EdgeConstraint subclass: #FixedTop
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FixedTop guid: (GUID fromString: '{4a5acee0-d082-4537-9e62-861657a0e6f1}')!

FixedTop comment: ''!

!FixedTop categoriesForClass!Unclassified! !

!FixedTop methodsFor!

variable
	^frame top! !

!FixedTop categoriesForMethods!
variable!public! !
!

