"Filed out from Dolphin Smalltalk"!

EdgeConstraint subclass: #FixedLeft
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FixedLeft guid: (GUID fromString: '{65eead8b-e132-497c-a25d-a2af24262582}')!

FixedLeft comment: ''!

!FixedLeft categoriesForClass!Unclassified! !

!FixedLeft methodsFor!

variable
	^frame left! !

!FixedLeft categoriesForMethods!
variable!public! !
!

