"Filed out from Dolphin Smalltalk"!

EdgeConstraint subclass: #FixedRight
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FixedRight guid: (GUID fromString: '{cc44dbe3-206b-4c65-8b1d-8613c70b0642}')!

FixedRight comment: ''!

!FixedRight categoriesForClass!Unclassified! !

!FixedRight methodsFor!

variable
	^frame right! !

!FixedRight categoriesForMethods!
variable!public! !
!

