"Filed out from Dolphin Smalltalk"!

EdgeConstraint subclass: #FixedBottom
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FixedBottom guid: (GUID fromString: '{f414d2d2-83fe-4068-8e0f-369f17ffe8e6}')!

FixedBottom comment: ''!

!FixedBottom categoriesForClass!Unclassified! !

!FixedBottom methodsFor!

variable
	^frame bottom! !

!FixedBottom categoriesForMethods!
variable!public! !
!

