"Filed out from Dolphin Smalltalk"!

ConstraintSpec subclass: #HeightConstraint
	instanceVariableNames: 'height'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

HeightConstraint guid: (GUID fromString: '{3388af19-fb58-41a7-89bc-d60abd76d98f}')!

HeightConstraint comment: ''!

!HeightConstraint categoriesForClass!Unclassified! !

!HeightConstraint methodsFor!

height: anObject
	height := anObject! !

!HeightConstraint categoriesForMethods!
height:!public! !
!

