"Filed out from Dolphin Smalltalk"!

ConstraintSpec subclass: #WidthConstraint
	instanceVariableNames: 'width'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WidthConstraint guid: (GUID fromString: '{7ec8bd12-aa10-4996-96e2-533776e7edf3}')!

WidthConstraint comment: ''!

!WidthConstraint categoriesForClass!Unclassified! !

!WidthConstraint methodsFor!

width: anObject
	width := anObject! !

!WidthConstraint categoriesForMethods!
width:!public! !
!

