"Filed out from Dolphin Smalltalk"!

DrawImage subclass: #DrawTexture
	instanceVariableNames: 'texture'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawTexture guid: (GUID fromString: '{856cfa9c-5e3b-4589-834b-7abacb4c36c5}')!

DrawTexture comment: ''!

!DrawTexture categoriesForClass!Kernel-Objects! !

!DrawTexture methodsFor!

texture
	^texture!

texture: anObject
	texture := anObject! !

!DrawTexture categoriesForMethods!
texture!accessing!public! !
texture:!accessing!public! !
!

