"Filed out from Dolphin Smalltalk"!

DrawImage subclass: #DrawSurface
	instanceVariableNames: 'surface'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawSurface guid: (GUID fromString: '{db18547c-726d-4028-aa42-88111860024c}')!

DrawSurface comment: ''!

!DrawSurface categoriesForClass!Kernel-Objects! !

!DrawSurface methodsFor!

surface
	^surface!

surface: anObject
	surface := anObject! !

!DrawSurface categoriesForMethods!
surface!accessing!public! !
surface:!accessing!public! !
!

